# Generated by Django 4.2 on 2024-05-22 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                (
                    "save",
                    models.ManyToManyField(
                        related_name="playlist", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "zzim",
                    models.ManyToManyField(
                        related_name="zzim_playlists", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
